name: Get_Data

on:
  push:
    branches: [main]
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: "*/5 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - name: Installing dependencies
        run: pip install -r requirements.txt
      - name: Setting Enviroment Variables
        run: export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
      - name: Checking variable
        run: echo $PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
      - name: Running the Script
        run: python gtfs_data.py
      - name: Commit report
        run: |
          git config --global user.name 'Hussnain47'
          git config --global user.email 'hussnainilyas2344@gmail.com'
          git commit -am "Automated saving data"
          git push
